version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/app/docker/app.sh"]
    ports:
      - 8888:8000
    depends_on:
      - db